const { platforms, shapes, assetTypes } = require('../../../constants');

const { ROUND, SQUARE } = shapes;
const { ANDROID } = platforms;
const { LAUNCHICON } = assetTypes;

const launchIcons = [
  {
    name: 'appicon-square',
    dirName: 'mipmap-ldpi',
    dimensions: '36x36',
    density: 'ldpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mipmap-ldpi',
    dimensions: '36x36',
    density: 'ldpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-square',
    dirName: 'mippam-mdpi',
    dimensions: '48x48',
    density: 'mdpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mippam-mdpi',
    dimensions: '48x48',
    density: 'mdpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-square',
    dirName: 'mipmap-hdpi',
    dimensions: '72x72',
    density: 'hdpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mipmap-hdpi',
    dimensions: '72x72',
    density: 'hdpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-square',
    dirName: 'mipmap-xhdpi',
    dimensions: '96x96',
    density: 'xhdpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mipmap-xhdpi',
    dimensions: '96x96',
    density: 'xhdpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-square',
    dirName: 'mipmap-xxhdpi',
    dimensions: '144x144',
    density: 'xxhdpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mipmap-xxhdpi',
    dimensions: '144x144',
    density: 'xxhdpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-square',
    dirName: 'mipmap-xxxhdpi',
    dimensions: '512x512',
    density: 'xxxhdpi',
    shape: SQUARE,
    platform: ANDROID,
    type: LAUNCHICON,
  },
  {
    name: 'appicon-round',
    dirName: 'mipmap-xxxhdpi',
    dimensions: '512x512',
    density: 'xxxhdpi',
    shape: ROUND,
    platform: ANDROID,
    type: LAUNCHICON,
  },
];

module.exports = launchIcons;
