const { platforms, idioms } = require('../../../constants');

const { IOS } = platforms;
const { IPAD, IPHONE, IOSMARKETING } = idioms;

const launchIcons = [
  /*{
    name: 'Icon-App-20x20@1x',
    device: null,
    scale: '1x',
    dimensions: '20x20',
    size: '20x20',
    platform: IOS,
    idiom: IPHONE,
  },*/
  {
    name: 'Icon-App-20x20@2x',
    device: null,
    scale: '2x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPHONE,
    size: '20x20',
  },
  {
    name: 'Icon-App-20x20@3x',
    device: null,
    scale: '3x',
    dimensions: '60x60',
    platform: IOS,
    idiom: IPHONE,
    size: '20x20',
  },

  {
    name: 'Icon-Notification-20x20@1x',
    device: null,
    scale: '1x',
    dimensions: '20x20',
    platform: IOS,
    idiom: IPAD,
    size: '20x20',
  },
  {
    name: 'Icon-Notification-20x20@2x',
    device: null,
    scale: '2x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPAD,
    size: '20x20',
  },

  {
    name: 'Icon-App-29x29@1x',
    device: null,
    scale: '1x',
    dimensions: '29x29',
    platform: IOS,
    idiom: IPHONE,
    size: '29x29',
  },
  {
    name: 'Icon-App-29x29@2x',
    device: null,
    scale: '2x',
    dimensions: '58x58',
    platform: IOS,
    idiom: IPHONE,
    size: '29x29',
  },

  {
    name: 'Icon-Settings-29x29@1x',
    device: null,
    scale: '1x',
    dimensions: '29x29',
    platform: IOS,
    idiom: IPAD,
    size: '29x29',
  },
  {
    name: 'Icon-Settings-29x29@2x',
    device: null,
    scale: '2x',
    dimensions: '58x58',
    platform: IOS,
    idiom: IPAD,
    size: '29x29',
  },

  {
    name: 'Icon-App-29x29@3x',
    device: null,
    scale: '3x',
    dimensions: '87x87',
    platform: IOS,
    idiom: IPHONE,
    size: '29x29',
  },
  /*{
    name: 'Icon-App-40x40@1x',
    device: null,
    scale: '1x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPHONE,
    size: '40x40',
  },*/
  {
    name: 'Icon-App-40x40@2x',
    device: null,
    scale: '2x',
    dimensions: '80x80',
    platform: IOS,
    idiom: IPHONE,
    size: '40x40',
  },

  {
    name: 'Icon-Spotlight-40x40@1x',
    device: null,
    scale: '1x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPAD,
    size: '40x40',
  },
  {
    name: 'Icon-Spotlight-40x40@2x',
    device: null,
    scale: '2x',
    dimensions: '80x80',
    platform: IOS,
    idiom: IPAD,
    size: '40x40',
  },

  {
    name: 'Icon-App-40x40@3x',
    device: null,
    scale: '3x',
    dimensions: '120x120',
    platform: IOS,
    idiom: IPHONE,
    size: '40x40',
  },
  {
    name: 'Icon-App-50x50@1x',
    device: null,
    scale: '1x',
    dimensions: '50x50',
    platform: IOS,
    idiom: IPAD,
    size: '50x50',
  },
  {
    name: 'Icon-App-50x50@2x',
    device: null,
    scale: '2x',
    dimensions: '100x100',
    platform: IOS,
    idiom: IPAD,
    size: '50x50',
  },
  {
    name: 'Icon-App-57x57@1x',
    device: null,
    scale: '1x',
    dimensions: '57x57',
    platform: IOS,
    idiom: IPHONE,
    size: '57x57',
  },
  {
    name: 'Icon-App-57x57@2x',
    device: null,
    scale: '2x',
    dimensions: '114x114',
    platform: IOS,
    idiom: IPHONE,
    size: '57x57',
  },
  {
    name: 'Icon-App-60x60@2x',
    device: null,
    scale: '2x',
    dimensions: '120x120',
    platform: IOS,
    idiom: IPHONE,
    size: '60x60',
  },
  {
    name: 'Icon-App-60x60@3x',
    device: null,
    scale: '3x',
    dimensions: '180x180',
    platform: IOS,
    idiom: IPHONE,
    size: '60x60',
  },
  {
    name: 'Icon-App-72x72@1x',
    device: null,
    scale: '1x',
    dimensions: '72x72',
    size: '72x72',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-72x72@2x',
    device: null,
    scale: '2x',
    dimensions: '144x144',
    platform: IOS,
    idiom: IPAD,
    size: '72x72',
  },
  {
    name: 'Icon-App-76x76@1x',
    device: null,
    scale: '1x',
    dimensions: '76x76',
    platform: IOS,
    idiom: IPAD,
    size: '76x76',
  },
  {
    name: 'Icon-App-76x76@2x',
    device: null,
    scale: '2x',
    dimensions: '152x152',
    platform: IOS,
    idiom: IPAD,
    size: '76x76',
  },
  {
    name: 'Icon-App-83.5x83.5@2x',
    device: null,
    scale: '2x',
    dimensions: '167x167',
    platform: IOS,
    idiom: IPAD,
    size: '83.5x83.5',
  },
  {
    name: 'Icon-AppStore-1024x1024@1x.png',
    device: null,
    scale: '1x',
    dimensions: '1024x1024',
    platform: IOS,
    idiom: IOSMARKETING,
    size: '1024x1024',
  },
];

module.exports = launchIcons;
