const { platforms, idioms } = require('../../../constants');

const { IOS } = platforms;
const { IPAD, IPHONE, IOSMARKETING } = idioms;

const launchIcons = [
  {
    name: 'Icon-App-20x20@1x',
    device: null,
    scale: '1x',
    dimensions: '20x20',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-20x20@2x',
    device: null,
    scale: '2x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-20x20@3x',
    device: null,
    scale: '3x',
    dimensions: '60x60',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-29x29@1x',
    device: null,
    scale: '1x',
    dimensions: '29x29',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-29x29@2x',
    device: null,
    scale: '2x',
    dimensions: '58x58',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-29x29@3x',
    device: null,
    scale: '3x',
    dimensions: '87x87',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-40x40@1x',
    device: null,
    scale: '1x',
    dimensions: '40x40',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-40x40@2x',
    device: null,
    scale: '2x',
    dimensions: '80x80',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-40x40@3x',
    device: null,
    scale: '3x',
    dimensions: '120x120',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-50x50@1x',
    device: null,
    scale: '1x',
    dimensions: '50x50',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-50x50@2x',
    device: null,
    scale: '2x',
    dimensions: '100x100',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-57x57@1x',
    device: null,
    scale: '1x',
    dimensions: '57x57',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-57x57@2x',
    device: null,
    scale: '2x',
    dimensions: '114x114',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-60x60@1x',
    device: null,
    scale: '1x',
    dimensions: '60x60',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-60x60@2x',
    device: null,
    scale: '2x',
    dimensions: '120x120',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-60x60@3x',
    device: null,
    scale: '3x',
    dimensions: '180x180',
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Icon-App-72x72@1x',
    device: null,
    scale: '1x',
    dimensions: '72x72',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-72x72@2x',
    device: null,
    scale: '2x',
    dimensions: '144x144',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-76x76@1x',
    device: null,
    scale: '1x',
    dimensions: '76x76',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-76x76@2x',
    device: null,
    scale: '2x',
    dimensions: '152x152',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-76x76@3x',
    device: null,
    scale: '3x',
    dimensions: '228x228',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Icon-App-83.5x83.5@2x',
    device: null,
    scale: '2x',
    dimensions: '167x167',
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'ItunesArtwork@2x.png',
    device: null,
    scale: '2x',
    dimensions: '1024x1024',
    platform: IOS,
    idiom: IOSMARKETING,
  },
];

module.exports = launchIcons;
