const { orientations, platforms, idioms } = require('../../../constants');

const { PORTRAIT, LANDSCASPE } = orientations;
const { IOS } = platforms;
const { IPAD, IPHONE } = idioms;

const splashScreens = [
  // PORTRAIT
  {
    name: 'Default-Portrait-1366h@2x',
    device: '12.9" iPad Pro',
    scale: '2x',
    dimensions: '2048x2732',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Portrait-1194h@2x',
    device: '11" iPad Pro 10.5" iPad Pro',
    scale: '2x',
    dimensions: '1668x2388',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Portrait-1024h@2x',
    device: '9.7" iPad Pro 7.9" iPad mini 9.7" iPad Air 9.7" iPad',
    scale: '2x',
    dimensions: '1536x2048',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Portrait-1112h@2x',
    device: '10.5" iPad Air',
    scale: '2x',
    dimensions: '1668x2224',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Portrait-1080h@2x',
    device: '10.2" iPad',
    scale: '2x',
    dimensions: '1620x2160',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Portrait-926h@3x',
    device: 'iPhone 12 Pro Max',
    scale: '3x',
    dimensions: '1284x2778',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Default-Portrait-844h@3x',
    device: 'iPhone 12 Pro iPhone 12',
    scale: '3x',
    dimensions: '1170x2532',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Default-Portrait-812h@3x',
    device: 'iPhone 12 mini iPhone 11 Pro iPhone XS iPhone X',
    scale: '3x',
    dimensions: '1125x2436',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Default-Portrait-896h@3x',
    device: 'iPhone 11 Pro Max iPhone XS Max',
    scale: '3x',
    dimensions: '1242x2688',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Default-Portrait-896h@2x',
    device: 'iPhone 11 iPhone XR',
    scale: '2x',
    dimensions: '828x1792',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },

  {
    name: 'Default-Portrait-667h@2x',
    device: 'iPhone 8 iPhone 7 iPhone 6s iPhone 6 4.7" iPhone SE',
    scale: '2x',
    dimensions: '750x1334',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  {
    name: 'Default-Portrait-568h@2x',
    device: '4" iPhone SE',
    scale: '2x',
    dimensions: '640x1136',
    orientation: PORTRAIT,
    platform: IOS,
    idiom: IPHONE,
  },
  // LANDSCAPE
  {
    name: 'Default-Landscape-1366h@2x',
    device: '12.9" iPad Pro',
    scale: '2x',
    dimensions: '2732x2048',
    orientation: LANDSCASPE,
    platform: IOS,
    subtype: '1366h',
    idiom: IPAD,
  },
  {
    name: 'Default-Landscape-1194h@2x',
    device: '11" iPad Pro 10.5" iPad Pro',
    scale: '2x',
    dimensions: '2388x1668',
    orientation: LANDSCASPE,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Landscape-1024h@2x',
    device: '9.7" iPad Pro 7.9" iPad mini 9.7" iPad Air 9.7" iPad',
    scale: '2x',
    dimensions: '2048x1536',
    orientation: LANDSCASPE,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Landscape-1112h@2x',
    device: '10.5" iPad Air',
    scale: '2x',
    dimensions: '2224x1668',
    orientation: LANDSCASPE,
    platform: IOS,
    idiom: IPAD,
  },
  {
    name: 'Default-Landscape-1080h@2x',
    device: '10.2" iPad',
    scale: '2x',
    dimensions: '2160x1620',
    orientation: LANDSCASPE,
    platform: IOS,
    idiom: IPAD,
  },
];

module.exports = splashScreens;
